[project]
name = "yoshi-cli"
version = "0.2.0"
authors = [
  { name="Christian Cleberg", email="hello@cleberg.net" },
]
description = "A password manager for the command line."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "cryptography",
    "prettytable",
]

[project.urls]
Homepage = "https://github.com/ccleberg/yoshi"
Issues = "https://github.com/ccleberg/yoshi/issues"

[project.scripts]
yoshi = "yoshi.cli:yoshi"
