[project]
name = "devpkg"
version = "0.2.0"
description = "Dev tools for Python packages"
authors = [{ name = "Danny Stewart", email = "danny@stewart.cc" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["packaging (>=24.2)", "requests (>=2.32.3)"]

[tool.poetry.group.dev.dependencies]
mypy = ">=1.15.0"
pdoc = ">=15.0.1"
pre-commit = ">=4.2.0"
ruff = ">=0.11.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
