[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "kuhl-haus-metrics"
version = "0.2.5"
description = "Application logging and instrumentation"
authors = [
    { name = "Tom Pounders", email = "git@oldschool.engineer" },
]
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
]
dependencies = [
    "fastapi~=0.115.11",
    "importlib_metadata~=8.6.1",
    "dataclasses-json~=0.6.7",
    "importlib-metadata~=8.6.1",
]

[project.license]
file = "LICENSE.txt"

[project.urls]
Homepage = "https://github.com/kuhl-haus"
Documentation = "https://github.com/kuhl-haus/kuhl-haus-metrics/wiki"
Source = "https://github.com/kuhl-haus/kuhl-haus-metrics.git"
Changelog = "https://github.com/kuhl-haus/kuhl-haus-metrics/commits"
Tracker = "https://github.com/kuhl-haus/kuhl-haus-metrics/issues"

[project.optional-dependencies]
testing = [
    "setuptools~=76.1.0",
    "pdm-backend",
    "pytest~=8.3.5",
    "pytest-cov~=6.0.0",
    "pytest-asyncio",
    "httpx",
    "starlette~=0.46.1",
]

[tool.setuptools]
zip-safe = true
include-package-data = true

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [
    "src",
]
exclude = [
    "tests",
]

[tool.pytest.ini_options]
addopts = [
    "--verbose",
]
norecursedirs = [
    "dist",
    "build",
    ".tox",
]
testpaths = [
    "tests",
]

[tool.devpi.upload]
no_vcs = 1
formats = [
    "bdist_wheel",
]

[tool.flake8]
max_line_length = 88
extend_ignore = [
    "E203",
    "W503",
]
exclude = [
    ".tox",
    "build",
    "dist",
    ".eggs",
    "docs/conf.py",
]

[tool.pyscaffold]
version = "4.6"
package = "metrics"
extensions = [
    "namespace",
]
namespace = "kuhl_haus"

[tool.pdm]
distribution = true

[tool.pdm.build]
package-dir = "src"
includes = [
    "src/kuhl_haus",
]
