[project]
name = "automatic-youtube-maker-story"
version = "0.1.0"
description = ""
authors = [
    {name = "William Ferreira",email = "33575357+illiamw@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "gitpython (>=3.1.44,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)"
]

[tool.poetry]
packages = [{include = "automatic_youtube_maker_story", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
