[project]
name = "ngm-remove"
version = "0.0.9"
description = "Remove files/folders. Not drop-in replacement for rm, though"
readme = "docs/README.md"
authors = [
    { name = "Aibulat", email = "ngmaibulat@gmail.com" }
]
requires-python = ">=3.8"
dependencies = []

[project.scripts]
remove = "ngm_remove:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
