[project]
name = "story-children-video-maker"
version = "0.1.2"
home-page = "https://github.com/illiamw/illiamw"
description = ""
authors = [
    {name = "William Ferreira",email = "33575357+illiamw@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "moviepy (>=2.1.2,<3.0.0)"
]

[tool.poetry]
packages = [{include = "story_children_video_maker", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
