[project]
name = "walking-man"
version = "0.2.8"
description = "A friendly companion while you wait"
authors = [{ name = "Danny Stewart", email = "danny@stewart.cc" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["polykit (>=0.1.1)"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Shells",
    "Topic :: System :: System Shells",
    "Topic :: Utilities",
]

[tool.poetry.group.dev.dependencies]
blessed = "^1.20.0"
mypy = ">=1.15.0"
pdoc = ">=15.0.1"
pre-commit = "^4.2.0"
ruff = ">=0.11.4"
enviromancer = { path = "../enviromancer", develop = true }
logician = { path = "../logician", develop = true }
polykit = { path = "../polykit", develop = true }

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
walking-man = "walking_man.main:walking_man_adventure"
