[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "MEDCNN"
version = "0.0.2"
authors = [
  { name="Kishore Kumar Tarafdar", email="kishorektarafdar@gmail.com" },
]
description = "Multiresolution Encoder-Decoder Convolutional Neural Network (MEDCNN) without attentions"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering",
  "Intended Audience :: Science/Research"
]
license = "GPL-3.0-or-later"
license-files = [ "LICENSE" ]

[project.urls]
Homepage = "https://github.com/kkt-ee/MEDCNN"
Issues = "https://github.com/kkt-ee/MEDCNN/issues"