[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "naeural_core"
version = "7.7.45"
authors = [
  { name="Andrei Ionut Damian", email="andrei.damian@me.com" },
  { name="Stefan Saraev", email="saraevstefan@gmail.com" },
  { name="Cristan Bleotiu", email="cristibleotiu@gmail.com" },
]
description = "Ratio1 Core is the backbone of the Ratio1 Edge Protocol."
readme = "README.md"
requires-python = ">=3.10,<3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "torch",
  "torchvision",
  "torchaudio",
  "paho-mqtt>=1.6",
  "pika>=1.3",
  "pynvml>=11.4",
  "pyyaml>=6.0",
  "pyarrow>=15",
  "ratio1>=1.0.0",
  "minio",
  "gql",
  "opencv-python-headless",
  "decord",
  "accelerate==0.30.1",
  "bitsandbytes==0.43.1",
  "tokenizers>=0.14.1",
  "sentencepiece",
  "seaborn",
  "pandas",
  "shapely",
  "scikit-learn",
  "scikit-image",
  "dropbox",
  "pymssql",
  "h5py",
  "unidecode",
  "transformers>=4.38.0",
  "cryptography==42.0.7",
  "onnx",
  "openvino==2024.1.0",
  "onnxruntime-openvino==1.17.1",
  "onnxsim",
  "fastapi",
  "uvicorn",
  "pydantic",
  "bs4",
  "web3",
  "nvidia-cudnn-cu12<9.0",
  "decentra_vision",
]

[project.urls]
"Homepage" = "https://github.com/Ratio1/naeural_core"
"Bug Tracker" = "https://github.com/Ratio1/naeural_core/issues"