[project]
name = "dsbase"
version = "0.5.0b2"
description = "Delightful Python utility library with power and personality"
authors = [{ name = "Danny Stewart", email = "danny@stewart.cc" }]
urls = { repository = "https://github.com/dannystewart/dsbase" }
readme = "README.md"
license = "LGPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.12,<3.14"
dependencies = [
    "enviromancer (>=0.1.3)",
    "halo (>=0.0.31)",
    "logician (>=0.2.4)",
    "natsort (>=8.4.0,<9.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "send2trash (>=1.8.3,<2.0.0)",
    "textparse (>=0.1.0)",
    "types-requests (>=2.32.0.20250328,<3.0.0.0)",
    "types-send2trash (>=1.8.2.7,<2.0.0.0)",
    "walking-man (>=0.2.1)",
]

[tool.poetry.group.dev.dependencies]
mypy = ">=1.15.0"
pdoc = ">=15.0.1"
pre-commit = ">=4.2.0"
ruff = ">=0.11.2"
enviromancer = { path = "../enviromancer", develop = true }
logician = { path = "../logician", develop = true }
textparse = { path = "../textparse", develop = true }
walking-man = { path = "../walking-man", develop = true }

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
