[project]
name = "iplooker"
version = "0.1.8"
description = "Look up location, ISP, and more about an IP address from multiple sources"
authors = [{ name = "Danny Stewart", email = "danny@stewart.cc" }]
urls = { repository = "https://github.com/dannystewart/iplooker" }
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "logician (>=0.3.4)",
    "polykit (>=0.1.1)",
    "pycountry (>=24.6.1,<25.0.0)",
    "requests (>=2.32.3,<3.0.0)",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Networking",
    "Topic :: Utilities",
]

[tool.poetry.group.dev.dependencies]
ruff = ">=0.11.4"
mypy = ">=1.15.0"
enviromancer = { path = "../enviromancer", develop = true }
logician = { path = "../logician", develop = true }
polykit = { path = "../polykit", develop = true }
walking-man = { path = "../walking-man", develop = true }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
iplooker = "iplooker.ip_lookup:main"
