[build-system]
requires = ["setuptools>=71.1.0","setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "vespricetracker"
version = "1.1.7"
requires-python = ">=3.11.6"
authors = [
  {name = "Carlos Florez", email = "carlos@florez.co.uk"}
]
maintainers = [
  {name = "Carlos Florez", email = "carlos@florez.co.uk"}
]
description = ""
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "colorlog==6.4.0",
  "requests==2.32.3",
  "selenium==4.29.0",
  "pyyaml==6.0.1",
  "toml==0.10.2",
  "pywin32==306;sys_platform == 'win32'",
  "simplejson==3.20.1",
  "boto3==1.37.22"
]

[project.scripts]
vespricetracker = "vespricetracker.__main__:main"

[project.urls]
Repository = "https://github.com/florez-carlos/vespricetracker"
