[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gate-manager"
version = "2.7.13"
description = "A package for controlling and managing gate voltages in quantum devices."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
  { name = "Chen Huang", email = "chen.huang23@imperial.ac.uk" }
]
license = "MIT"
urls = { Homepage = "https://github.com/chenx820/gate-manager" }
requires-python = ">=3.6"
dependencies = [
    "nanonis_spm",
    "matplotlib",
    "numpy",
    "tqdm",
    "conductorquantum"
]
classifiers = [
    "Programming Language :: Python :: 3"
]

[tool.hatch.build.targets.wheel]
packages = ["gate_manager"]
