[project]
name = "robeex-ai-drone-api"
version = "0.1.0"
description = ""
authors = [
    {name = "RoBeeX Robotics",email = "robeex.robotics@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    "freetype-py (>=2.5.1,<3.0.0)",
    "cvzone[optional] (>=1.6.1,<2.0.0)",
    "mediapipe[optional] (>=0.10.21,<0.11.0)"
]

[tool.poetry]
packages = [{include = "robeex_ai_drone_api", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
