[build-system]
requires = [
    "setuptools==68.0.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "gru"
version = "0.0.1rc39"
description = "Canso Platform's Python package for Data & Machine Learning Usecases"
readme = "README.md"
authors = [
  { name="Canso Platform Development Team", email="platform-engineers@yugen.ai" },
]
license = {file = 'LICENSE'}
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.31.0",
    "typing==3.7.4.3",
    "chardet==5.1.0",
    "click>=8.1.7",
    "fire>=0.7.0",
    "pydantic>=2.6.3",
    "cookiecutter>=2.6.0",
    "langgraph>=0.2.50",
    "fastapi>=0.115.5",
    "uvicorn>=0.32.0",
    "langgraph-checkpoint-postgres>=2.0.3",
    "psycopg[binary,pool]",
    "celery>=5.5.0rc4", # TODO: change to 5.5.0 stable version as soon as it is released
    "redis>=5.2.0",
    "websockets>=14.1",
    "termcolor>=2.5.0",
    "PyGithub>=2.5.0",
    "pika>=1.3.2",
    "pymilvus>=2.5.4",
    "boto3>=1.37.1"
]


[project.urls]
homepage = 'https://yugen-ai-gru.readthedocs-hosted.com/en/latest/'
documentation = 'https://yugen-ai-gru.readthedocs-hosted.com/en/latest/'
repository = 'https://github.com/Yugen-ai/gru'

[project.scripts]
yugenml = "gru.cookiecutter.mlops_templates_cli:mlops_template_cli"
yserve = "gru.ml_serving.server:serve"
gru = "gru.cli:main"
canso = "gru.canso_cli:main"