[project]
name = "story-chilren-gemma3"
version = "0.1.8"
home-page = "https://github.com/illiamw/illiamw"
description = "Prompt programável para geração de histórias infantis pensado para videos no youtube de 1 minuto"
authors = [
    {name = "William Ferreira",email = "33575357+illiamw@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.8,<4.0"
dependencies = [
    "ollama (>=0.4.7,<0.5.0)",
    "regex (>=2024.11.6,<2025.0.0)",
    "tqdm (>=4.67.1,<5.0.0)"
]

[tool.poetry]
packages = [{include = "story_chilren_gemma3", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
