[project]
name = "timecapsule"
version = "0.1.2"
description = "Human-friendly datetime handling for Python"
authors = [{ name = "Danny Stewart", email = "danny@stewart.cc" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "devpkg (>=0.2.0)",
    "python-dateutil (>=2.9.0.post0)",
    "tzlocal>=5.3.1",
]

[tool.poetry.group.dev.dependencies]
mypy = ">=1.15.0"
pdoc = ">=15.0.1"
pre-commit = ">=4.2.0"
ruff = ">=0.11.2"
devpkg = { path = "../devpkg", develop = true }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
