[tool.poetry]
name = "xlin"
version = "0.1.16"
description = "toolbox for LinXueyuan"
authors = ["XiChen <23211526+LinXueyuanStdio@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
loguru = "*"
pandas = "*"
pyexcel = "*"
pyexcel-xls = "*"
pyexcel-xlsx = "*"
xlsxwriter = "*"
tqdm = "*"
pyyaml = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
