[build-system]
requires = [ "setuptools", "wheel", "poetry", "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "roc-dingo"
version = "1.5.4"
readme = "README.md"
license = "CECILL-2.1"
repository = "https://gitlab.obspm.fr/ROC/Pipelines/Plugins/DINGO"
description = "Data INgestOr (DINGO) plugin is used to ingest data into the ROC pipeline database"
authors = [ "ROC Team <roc.support@sympa.obspm.fr>",]
exclude = [ "bump_descriptor.py",]
[[tool.poetry.packages]]
include = "roc"

[tool.mypy]
[[tool.mypy.overrides]]
module = [ "poppy.*", "roc.*", "spice_manager.*", "pandas.*", "scipy.*", "h5py.*", "pytest.*",]
ignore_missing_imports = true

[tool.poetry.dependencies]
python = ">=3.9,<4"
requests = "^2"
numpy = ">=1.20,<3"
pandas = ">1, <3"
h5py = "^3.7"
jinja2 = "^3"
spacepy = ">=0.7,<1"
xmltodict = ">=0.12,<1.0"
sqlalchemy = "^2"
alembic = "^1"
spice_manager = "*"
poppy-core = ">0.12.0"
poppy-pop = ">0.12.0"
roc-idb = "^1"
roc-rpl = "^1"

[tool.poetry.group.dev.dependencies]
pytest = "<9"
pytest-cov = "<6"
pytest-timeout = "<3"
pre-commit = "^3"
mypy = "^1"
ruff = "*"
toml = "*"
PyYAML = "*"
