[project]
name = "antools"
version = "2025.5.0"
description = "My project"
authors = [
    {name = "AntonÃ­n Drozda",email = "adrozda.dev@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
