[project]
name = "embedd-all"
version = "0.0.942"
description = "Embedd (docs, pdfs, excels, csv etc) -> RAG -> Query with LLMs"
authors = [
    { name = "Arnab Bhattacharya", email = "arnab.bhattacharya28122000@gmail.com" }
]
maintainers = [
    { name = "Arnab Bhattacharya", email = "arnab.bhattacharya28122000@gmail.com" }
]
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.2",
    "langchain-community>=0.2.2",
    "langchain>=0.2.2",
    "pypdf>=4.2.0",
    "pinecone==6.0.2",
    "anthropic>=0.32.0",
    "voyageai>=0.2.3",
    "python-docx>=1.1.2",
    "pypandoc-binary>=1.13",
    "pytest>=8.3.4",
    "openai>=1.59.5",
]
readme = "README.md"
requires-python = ">= 3.8"


[project.urls]
Homepage = "https://github.com/Arnab28122000/embed-all"
Repository = "https://github.com/Arnab28122000/embed-all"
"Bug Tracker" = "https://github.com/Arnab28122000/embed-all/issues"
Documentation = "https://github.com/Arnab28122000/embed-all/blob/main/README.md"

[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
universal = true
dev-dependencies = []

[tool.hatch.metadata]
name = "embedd-all"
version = "0.0.939"
description = "Embedd (docs, pdfs, excels, csv etc) -> RAG -> Query with LLMs"
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["embedd_all"]
