[project]
name = "qass-tools-networking"
version = "4.0.0a1"
authors = [
  {name="Oliver Kowollik", email="okowollik@qass.net" },
  {name="Sammy Joe LÃ¼ling", email="slueling@qass.net" }
]
description = "Networking package for qass_tools"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "PySide2",                    # Python Server client
    "tqdm>=4.64.0",               # Analyzer_SSH
    "retry",                      # Analyzer_Remote
    "paramiko",                   # Analyzer_SSH
    "numpy >=1.19.5",             # Analyzer_Remote
]

[project.optional-dependencies]
# development dependency groups
developers = [
    "pytest >= 7.1.2",
    "enum-tools",
    "Sphinx",
]
# here can be later added another more specified group e.g. only testing test =[]
# and developer can reference that 'my-package[test]',
[project.urls]
Homepage = "https://qass.github.io/"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
