[project]
name = "hotpod-cli"
version = "1.2.0"
description = "A command line tool for GCS"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "JDCloud AIDC Team", email = "your.email@example.com"}
]
dependencies = [
    "click>=8.1.8",
    "setuptools>=78.0.2",
    "click-help-colors>=0.9.1",
    "click-option-group>=0.5.3",
    "click-spinner>=0.1.10",
    "jdcloud-sdk>=1.6.88",
    "python-dotenv>=1.0.0",
    "litellm==1.64.1",
    "paramiko==3.4.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/yourusername/hotpod-cli"

[project.scripts]
hotpod = "hotpod_cli.main:main"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"