[project]
name = "anilibria"
version = "0.1.6"
description = "Python API wrapper for AniLibria"
authors = [
    {name = "anekobtw",email = "krolexonder@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "m3u8-to-mp4 (>=0.1.11,<0.2.0)",
    "requests (>=2.32.3,<3.0.0)"
]
repository = "https://github.com/anekobtw/anilibria"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
