[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyBCRAdata"
version = "0.2.0"
authors = [
    { name = "Diego Mora", email = "morabdiego@gmail.com" },
]
description = "A Python client for accessing BCRA (Banco Central de la RepÃºblica Argentina) "
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Science/Research",
    "License :: Free for non-commercial use",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Office/Business :: Financial",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "pandas>=1.0.0",
    "requests>=2.25.0",
    "typing-extensions>=4.0.0",  # Added for better type hint support
]

[project.urls]
"Homepage" = "https://github.com/morabdiego/pyBCRA"
"Bug Tracker" = "https://github.com/morabdiego/pyBCRA/issues"
"Documentation" = "https://github.com/morabdiego/pyBCRA#readme"

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "pyBCRAdata",
    "pyBCRAdata.api",
    "pyBCRAdata.config",
    "pyBCRAdata.utils"
]

[tool.setuptools.package-data]
"pyBCRdata" = [
    "cert/*.pem",
    "py.typed"  # Added for type hint support
]
