[project]
name = "eodh-jpyauth"
version = "0.1.3"
description = "A JupyterHub OIDC authenticator for Keycloak"
readme = "README.md"
authors = [
    { name = "Steven Gillies", email = "steven.gillies@telespazio.com" }
]
requires-python = ">=3.10"
dependencies = [
    "jupyterhub-kubespawner>=7.0.0",
    "oauthenticator>=17.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "dockerspawner>=14.0.0",
    "ruff>=0.9.7",
]
