[tool.poetry]
name = "briton"
version = "0.1.42.dev3"
description = "Python component of using Briton"
authors = ["Pankaj Gupta <pankaj@baseten.co>"]
license = "MIT"
readme = "README.md"
exclude = ["scripts/*.py"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
grpcio = "^1.62.3"
grpcio-tools = "^1.62.3"
transformers = "4.45.1"
pydantic = "^2.9.2"
fastapi = "^0.114.0"
huggingface-hub = "^0.25.2"
hf-transfer = "^0.1.8"
openai = "^1.51.2"
psutil = "5.9.4"
partial-json-parser = "^0.2.1.1.post5"
sentencepiece = "^0.2.0"
jinja2 = "^3.1.6"
datasets = "^3.4.1"
prometheus-client = ">=0.16.0"
briton-lib = "^0.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ipdb = "^0.13.13"
ipython = "^8.28.0"
pytest-asyncio = "^0.25.2"
black = "^24.10.0"
isort = "^5.13.2"
twine = "^5.1.1"
mypy-protobuf = "^3.6.0"
aiohttp = "^3.10.10"
toml = "^0.10.2"
pytest-cov = "^6.0.0"
truss = "^0.9.70"

[tool.isort]
profile = "black"
known_first_party = ["briton"]

[tool.poetry.scripts]
download_trtllm_config = "scripts.download_trtllm_config:main"
copy_truss_server = "scripts.copy_truss_server:main"
update_dependencies = "scripts.update_dependencies:main"
run_truss = "scripts.run_truss:main"
