[project]
name = "narration-xtts2"
version = "1.0.5"
home-page = "https://github.com/illiamw/illiamw"
description = "Projeto que baseado em um json cria narrações frase a frase em uma lista de frases, com flexibilidade de parametros do modelo XTTS2"
authors = [
    {name = "William Ferreira",email = "33575357+illiamw@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "torch (>=2.3,<2.4)",
    "torchvision (>=0.18,<0.19)",
    "torchaudio (>=2.3,<2.4)",
    "tts (>=0.22.0,<0.23.0)",
    "cutlet (>=0.5.0,<0.6.0)",
    "deepspeed (==0.15)",
    "tqdm (>=4.67.1,<5.0.0)",
    "fugashi (>=1.4.0,<2.0.0)",
    "mecab-python3 (>=1.0.10,<2.0.0)"
]





[tool.poetry]
packages = [{include = "narration_xtts2", from = "src"}]




[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"


[tool.poetry.dependencies]
torch = {source = "pytorch-gpu"}
torchvision = {source = "pytorch-gpu"}
torchaudio = {source = "pytorch-gpu"}

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.33.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
