[project]
name = "poetry-common-demo"
version = "0.1.0"
description = ""
authors = [
    {name = "Jeremy Freiburger [I]",email = "jfreiburger@tesla.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "poetry_common_demo", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
