[project]
name = "my-trainer"
version = "0.1.0"
description = ""
authors = [
    {name = "vpakala_euc",email = "vpakala@omnissa.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "my-rnn>=0.1.6",
    "my-gentxt-utils"
]

[tool.poetry]
packages = [{include = "my_train", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
train = "my_train.train_rnn:main"
