# Project Configuration
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sandwich_tag"
version = "0.1.0"
requires-python = ">=3.10, <4.0"
description = "A django template tag that simplifies nested templates."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "Jacob Tumak", email = "jacobtumak@users.noreply.github.com" }
]
keywords = ["sandwich", "sandwich_tag", "django-sandwich-tag",]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Framework :: Django",
]
dependencies = [
    "django",
]

[dependency-groups]
dev = [
    { include-group = "format" },
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "utils" },
    { include-group = "build" },
]
test = [
    "pytest",
    "pytest-django",
    "pytest-cov",
    "pytest-sugar",
]
utils = [
    "tox",
    "invoke",
    "bumpver",
    "pip-tools",
]
format = ["black", "isort", ]
lint = ["flake8", "flake8-bugbear", ]
build = ["build", "twine", ]

[project.urls]
Homepage = "https://github.com/jacobtumak/sandwich"
Repository = "https://github.com/jacobtumak/sandwich"


# Other Tools
[tool.setuptools]
include-package-data = true  # True by default, declarations in MANIFEST.in

[tool.setuptools.packages.find]
include = ["sandwich_tag"]

[tool.bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version: {old_version} --> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['version = "{version}"']
"README.md" = ['Version: {version}']
"sandwich/__init__.py" = ['__version__ = "{version}"']
"docs/source/conf.py" = ["version = '{version}'", "release = '{version}'"]

[tool.black]
target-version = ["py39", "py310", "py311"]

[tool.isort]
profile = "black"
skip_gitignore = true
