[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "db-model-trainer"
version = "0.1.2"
authors = [
    { name="Ben Mackenzie", email="ben.mackenzie@example.com" },
]
description = "A package for processing YAML in Databricks"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "pyyaml>=6.0.1",
    "click>=8.0.0",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/db-model-trainer"
"Bug Tracker" = "https://github.com/yourusername/db-model-trainer/issues"

[project.scripts]
yaml-processor = "db_model_trainer.cli:run_cli" 